### PR TITLE
CircleCI: Fix key -> keys list

### PR DESCRIPTION
**Pull request by sirreal**
Multiple `key` is not the same as `keys`. Allow this to fallback correctly.

### CODE REVIEW

**Comment by sirreal** [comment]
Seems to work:

```
npm-v1-et7p7EbN0qTnQ3orb0azlyQ8lf0W7xlMJbDJ2ENSGyM=-K5ncuwC0g0rFIBMHBmqr5VYY5RyyGKPdy5skO_lx8Xk=
```

Before it was (only the second checksum)

```
npm-v1-et7p7EbN0qTnQ3orb0azlyQ8lf0W7xlMJbDJ2ENSGyM=
```

**Comment by blowery** [comment]
Tests failed with a simple timeout, not because of this change. Re-running.

**Comment by blowery** [comment]
And nice catch @sirreal

**Comment by alisterscott** [comment]
I updated from master and all passing now - thanks for your commitment to improving the e2e tests!

**Pull request merged**
