### PR TITLE
Update Dependencies

### PR DESCRIPTION
**Pull request by bsessions85**
For #1282, I've updated the dependencies that we could. Magellan > 10.0.0 does not support Mocha and we were asked by Mailosaur to downgrade from 5.0.3 to 4.0.0 because we were overwhelming their systems somehow.

### CODE REVIEW

**Comment by alisterscott** [comment]
Thanks @bsessions85 

> we were asked by Mailosaur to downgrade from 5.0.3 to 4.0.0 because we were overwhelming their systems somehow

I think this was because we were using a new polling method - we could try upgrading the library but keeping our approach the same to see if this goes ok? What do you think?

**Comment by alisterscott** [comment]
Raised the Magellan issue here: https://github.com/Automattic/wp-e2e-tests/issues/1284

**Comment by bsessions85** [comment]
@alisterscott  I just looked at updating Mailosaur the polling feature we were using, waitFor, is the only real option for finding an email in the form we want it. The other option, search, returns a list of emails, but doesn't return any of the emails themselves. A second call would need to be made to get the full email. Do you think that would be worth the effort?

**Comment by alisterscott** [comment]
@bsessions85 can we leave our mailosaur code exactly the same and just update the client, or is the approach we're taking not compatible with the new client? If it's not, I'd say we should just stick with the old client for now - at least until Mailosaur tells us what we should do or releases a fix for `waitFor`

**Comment by bsessions85** [comment]
@alisterscott Yeah, they completely changed the methods so we'll just wait for a fix.

**Pull request merged**
