### PR TITLE
highlight element api

### PR DESCRIPTION
**Pull request by manoj9788**
Useful to see visually during the webdriver run

### CODE REVIEW

**Comment by manoj9788** [comment]
for now I have added this only to clickWhenClickable we can add the function call to other API's once its proved working. Its working fine in my local.

**Comment by hoverduck** [comment]
Works well for me.  My only thought is that before adding it to any other function calls is it might be useful to add a conditional check for the `CI` environment variable to disable the highlighting when we're running it without a visible window to watch.  That will avoid throwing off our visual diff tests.

**Comment by hoverduck** [comment]
Another option would be to make it configurable via a variable in the NODE_CONFIG setup.  That way it would be easy to turn on/off when you want it locally, and we just won't add it to the CI setup.

**Comment by manoj9788** [comment]
I agree, its good to add a On/Off flag.

**Pull request merged**
