### PR TITLE
Try setting dns prefetch disable

### PR DESCRIPTION
**Pull request by alisterscott**
Trying to solve ‘timeout: cannot determine loading status’ errors

### CODE REVIEW

**Comment by hoverduck** [comment]
The version of Chrome in the apt repository is still v54, but I was able to pull v56 directly from Google and install it.  [Didn't help](https://circleci.com/gh/Automattic/wp-e2e-tests/7204).

**Comment by alisterscott** [comment]
I'm going to try adding detailed webdriver logging to see if I can work out where the exception actually happens and whether there is a pattern or whether it's particular pages in our app etc.

**Comment by alisterscott** [comment]
The individual browsers didn't appear to fix our issues so it's probably best to revert this since it adds execution time to the suite

**Comment by hoverduck** [comment]
@alisterscott - Reverted - https://github.com/Automattic/wp-e2e-tests/pull/418

**Pull request merged**
