### PR TITLE
Put back classic editor comment test

### PR DESCRIPTION
**Pull request by Stojdza**
Changes in https://github.com/Automattic/wp-e2e-tests/pull/1729 caused that comments test is not passing for jetpack sites. I've removed `@jetpack` tag from `Commenting and replying to newly created post in Gutenberg Editor:` and put back test `Commenting and replying to newly created post:`.

To test: 
Make sure that `wp-comments-spec.js` is passing against jetpack sites.

### CODE REVIEW

**Comment by JavonDavis** [comment]
@Stojdza #1741 was merged and caused a conflict, resolved this and will merge once everything checks out!

**Comment by Stojdza** [comment]
@JavonDavis [This](https://github.com/Automattic/wp-e2e-tests/pull/1738/commits/99e9607bf612d429d23a8571a14a1d639ed3a73a#diff-979a2854d40d0d19fef064e6976e79cdR75) space caused a problem with tests execution. I fixed it and ran tests. Failed ones seem not related to this change. Is it good to go?

**Comment by JavonDavis** [comment]
> @JavonDavis This space caused a problem with tests execution. I fixed it and ran tests. Failed ones seem not related to this change. Is it good to go? 

My bad I actually resolved this through Github's online interface to test out that... Yep good to go!

**Comment by brbrr** [comment]
Thanks folks!

**Pull request merged**
