### PR TITLE
Add a payment button e2e test

### PR DESCRIPTION
**Pull request by alisterscott**
This adds an e2e test to add a payment button via the editor and make sure it appears on the front end of the site

### CODE REVIEW

**Comment by alisterscott** [comment]
@hoverduck I tried running this against a Jetpack site (bluehost) and it says a newer version of Jetpack was required even though the Jetpack version was the latest. Any ideas why?

**Comment by hoverduck** [comment]
Maybe the UI has changed in the last few days (sorry for the delayed review), but what I'm seeing now is this upgrade nudge:

image

If that's the case then I guess we need to just remove the `@jetpack` tag from this test and make a note in #650 that when we run the tests against non-free sites that we can add this test back in.

**Comment by alisterscott** [comment]
@hoverduck I think your image shows a different version of Jetpack is needed (not a different plan)? Where are you seeing that it needs a non-free Jetpack plan?

**Comment by hoverduck** [comment]
Oh you're right, I didn't even read the text...I just saw it's the standard upgrade nudge banner we use elsewhere.  And clicking the link takes you to the plans page... So either the text on the banner needs to be updated, or it should link to a different place, right?

**Comment by alisterscott** [comment]
Payment buttons do require a Jetpack plan so there's actually two separate issues here. I have removed this test from running on Jetpack sites for now as we don't use plans.

**Pull request merged**
