### PR TITLE
Themes: Update Theme Thumbnail Selector

### PR DESCRIPTION
**Pull request by ockham**
Companion PR to https://github.com/Automattic/wp-calypso/pull/27169

### CODE REVIEW

**Comment by ockham** [comment]
Ran this locally, and unfortunately got

```
TimeoutError: Timed out waiting for element with css selector of '.theme__thumbnail' to be clickable
```

**Comment by sirreal** [comment]
I pushed a fix for the theme selector 👍

**Comment by ockham** [comment]
Thanks a lot, Jon :heart:

**Comment by sirreal** [comment]
A follow-up fix was required which is intersting to understand: #1475

**Pull request merged**
