### PR TITLE
Add Featured image test

### PR DESCRIPTION
**Pull request by brbrr**
as requested in #302

### CODE REVIEW

**Comment by hoverduck** [comment]
Just adding a link to cross-reference this with the data-attribute PR: https://github.com/Automattic/wp-calypso/pull/17565

**Comment by brbrr** [comment]
Hm, that 'dirty' flag doesn't look like expected behavior. Featured image was deleted, so there no actual changes to be saved. For my understanding is a bug, and removing unexpected alert is kinda workaround. A better approach would be to issue a bug in wp-calypso. If you agree - I'll create an issue in the wp-calypso repo.

**Comment by rachelmcr** [comment]
> It's weird because adding/deleting images to the post by itself doesn't set the flag, but featured image does.

Uploading/deleting images in the site's media library from within the editor doesn't set the flag, but if you add images to the post content and then delete them it does. That's more analogous to adding/removing the featured image.

> Hm, that 'dirty' flag doesn't look like expected behavior. Featured image was deleted, so there no actual changes to be saved.

I tested other editor actions such as adding and deleting an image from the post content, adding and removing text in the post, and adding and removing tags/categories. In each case, the initial change sets the "dirty" flag but removing the change does not unset the "dirty" flag.

In that sense, the featured image behavior is consistent with how the AYS dialog works with other features in the editor, but I don't think it's ideal. Opening an issue in the wp-calypso repo to raise that seems like a good idea, and perhaps it will help shed light on the AYS bug in https://github.com/Automattic/wp-calypso/issues/9833.

**Comment by brbrr** [comment]
Committed workaround of wp-calypso/#17701. It should be removed once the issue is resolved.

**Pull request merged**
