### PR TITLE
Use generic CircleCI container

### PR DESCRIPTION
**Pull request by hoverduck**
Since we're controlling the Chromedriver version via npm now the only real reason left that we're using a custom Docker container is the Chrome version, which doesn't really buy us that much.

This PR keeps us on CircleCI 2.0, but uses one of their provided container images (which currently has Chrome v64, for the record).  This should greatly simplify changes down the line since we won't need to build/push a new image just to change versions.  And from what I've seen so far it looks like CircleCI will likely continue updating Chrome on newer images as new versions of Node come out, so that should keep us current.

I want to run this through a few times before merging it to watch out for timeouts (https://github.com/Automattic/wp-e2e-tests/issues/754).  And we'll need to merge a similar change into the Jetpack repo as well, as it expects to retain the `nvm` steps that I've removed here.  I'll give that end a try tomorrow, as I'm about to sign out for the day :smile: 

Also note that I based this branch off of #981, since we needed the updated `npm install` setup, and I didn't merge that one yet.

### CODE REVIEW

**Comment by alisterscott** [comment]
This looks good - we should update our wrapper repos to use the same CircleCI 2.0 containers as CircleCI 1.0 is being deprecated come October

**Comment by alisterscott** [comment]
> I want to run this through a few times before merging it to watch out for timeouts

Is there any difference between running headless chrome, or non-headless chrome under xvfb?

**Comment by alisterscott** [comment]
The caching wasn't working on re-runs in CircleCI so I updated the syntax a bit and it seems to be working now

**Comment by hoverduck** [comment]
> The caching wasn't working on re-runs in CircleCI so I updated the syntax a bit and it seems to be working now

Thanks :smile:

> Is there any difference between running headless chrome, or non-headless chrome under xvfb?

Effectively there shouldn't be.  I would hope that headless chrome would potentially have lower resource utilization since it's not actually drawing the screens, but I don't know that for sure.  It could just as easily use _more_ resources depending on how it's implemented behind the scenes.

I just know that when we turned this on the first time we ended up seeing a lot of unexplained timeouts, and I'm hoping that's been resolved with a newer version of Chrome. :crossed_fingers:

**Comment by hoverduck** [comment]
I've got the Jetpack PR ready here - https://github.com/Automattic/jetpack/pull/8942

They'll both need to be merged at the same time

**Pull request merged**
