### PR TITLE
Use mobile emulation in Chrome to get better screen size emulation

### LINKED ISSUE #1477: Resizing browser to mobile not working in CircleCI
I noticed resizing the browser in CircleCI isn't working

It's meant to be 400 pixels but example here: https://22741-57936731-gh.circle-artifacts.com/0/home/circleci/wp-e2e-tests/screenshots/FAILED-EN-MOBILE-can-add-a-new-product-via-the-products-menu-in-the-woo-store-sidebar-1537145347223.png

I tried updating Chromedriver to latest and the issue remains

### PR DESCRIPTION
**Pull request by bsessions85**
Fixes  #1477 

The resize wasn't working on Chrome and even setting the window size wasn't getting the correct window size. I switched it over to using the mobile emulation functionality and now it uses the correct, expected viewable area.

To Test:
Run tests in desktop and mobile view and make sure they pass and viewable area is correct.

### CODE REVIEW

**Comment by Stojdza** [comment]
This what I see when I run `BROWSERSIZE=desktop` and `BROWSERSIZE=mobile`. @bsessions85 did you see something similar? 

screen shot 2018-09-24 at 21 43 40
screen shot 2018-09-24 at 21 42 25

**Comment by bsessions85** [comment]
@Stojdza  Yes, that is what I see too. The browser window will be 1600x1200, but the viewable area will match what we are expecting.

**Comment by Stojdza** [comment]
Cool! Then it's good. I didn't understand that size will remain 1600x1200. 

Tests are passing as usual 👍

**Comment by alisterscott** [comment]
Great work on this - a nice approach for mobile screen sizes 👍

**Pull request merged**
