### PR TITLE
Using sha for dserve

### PR DESCRIPTION
**Pull request by bsessions85**
This should help with getting the correct version of calypso.live before we start the test.

Should be merged with https://github.com/Automattic/wp-e2e-tests-gh-bridge/pull/45

### CODE REVIEW

**Comment by bsessions85** [comment]
Tested in https://circleci.com/gh/Automattic/wp-e2e-tests-for-branches/11526#build-parameters/containers/0

**Comment by alisterscott** [comment]
Hi @bsessions85 

Thanks for taking this on, this looks good and worked well in my local testing:

`./run.sh -C -b fb14a04f61db4c18571a418fd7e1760886a040c0 `

I noticed that the `docs/running-tests.md` needs an update

One thought though, could we make this change backwards compatible so we could either use branch or hash for now? That way when we're merging this we won't get an issues with live branches being executed using the wrong parameters and trying to run branches against hashes etc.

Just an idea, perhaps another run.sh argument that kicks off a build with the hash instead of the branch, and then we can get this merged, then merge the other PRs that send the updated argument?

What do you think?

**Comment by bsessions85** [comment]
Yeah, that makes sense and is a good idea. I updated it and tested that it works with either one.

**Comment by alisterscott** [comment]
Tests well:

`./run.sh -C -b fb14a04f61db4c18571a418fd7e1760886a040c0`

**Pull request merged**
