### PR TITLE
Domains: No more privacy

### PR DESCRIPTION
**Pull request by aidvu**
Lower the count of products in cart.

### CODE REVIEW

**Comment by Stojdza** [comment]
@aidvu Test is failing because [there are still 2 products](https://26627-57936731-gh.circle-artifacts.com/1/home/circleci/wp-e2e-tests/screenshots/FAILED-EN-DESKTOP-can-then-see-the-secure-payment-page-with-the-correct-products-in-the-cart-1551126020095.png) in the cart. Does one of these two should miss?

**Comment by aidvu** [comment]
@Stojdza this is one of those cases where we need the `master` PR to land, for this to work. https://github.com/Automattic/wp-calypso/pull/30948

**Comment by Stojdza** [comment]
Oh, ok. Didn't know about that PR.

You could name this branch the same as wp-calypso branch so tests from this branch could run against wp-calypso PR.

**Comment by aidvu** [comment]
Oooooh, what you're saying is if the branch names are the same, it won't run on `master` but on that branch?

**Comment by Stojdza** [comment]
Exactly :) We've introduced that a few months ago in [this PR ](https://github.com/Automattic/wp-e2e-tests-gh-bridge/pull/62)

From FG page: _Sometimes you need to update the e2e test to match the changes introduced in your calypso PR. In that case, simply creating a branch with the same branch name as the calypso PR on the e2e test repo, and our CI setup will pair them automatically._

**Comment by aidvu** [comment]
In favor of https://github.com/Automattic/wp-e2e-tests/pull/1814.

**Pull request closed without merging**
