### PR TITLE
WIP:Update Tests for iframed Gutenberg

### PR DESCRIPTION
**Pull request by bsessions85**
This PR Is to update the tests to work on iframed Gutenberg

### CODE REVIEW

**Comment by Stojdza** [comment]
This PR matches changes proposed in https://github.com/Automattic/wp-calypso/pull/30451. Branch name matched with wp-calypso branch, so I'll reopen this. 

In PR https://github.com/Automattic/wp-e2e-tests/pull/1786 Signup tests were failing because wp-e2e version was newer than wp-calypso version on branch `try/calypsoify-iframe`

**Comment by Stojdza** [comment]
Tests results: https://circleci.com/gh/Automattic/wp-e2e-tests/26154

**Comment by gwwar** [comment]
@Automattic/flowpatrol cc @Stojdza @bsessions85 Let's not land Automattic/wp-e2e-tests#1784. Keep the diff, then update the branchname to match our next PR.

We'll drop the wpcalypso iframe flag in wp-calypso and keep that false for this feature. In the next follow up PR we'll enable it again so folks can continue with E2E test updates. We'll continue to drop this flag right before merge until we're further along in functionality.

**Comment by gwwar** [comment]
Next WIP branch on the Calypso side is https://github.com/Automattic/wp-calypso/pull/30401 or `add/gutengerg-calypsoify-media-modal`

**Comment by Stojdza** [comment]
I'm closing this because of https://github.com/Automattic/wp-calypso/pull/30529 - I made another e2e branch to match the name with wp-calypso branch

**Pull request closed without merging**
