### PR TITLE
Add/slack notification bot

### PR DESCRIPTION
**Pull request by brbrr**
Redesign of slack notifications by using slack bot API: https://api.slack.com/methods

Current issues:
- Make it work with magellan code(which isn't support `import` statements)
- Add message attachments

To test:
1. `export CIRCLE_BRANCH=master`
2. /node_modules/.bin/babel slack-bot.js  -o _slack-bot.js
3. JETPACKHOST=PRESSABLE ./node_modules/.bin/magellan --config=./magellan-jetpack.json --test=specs-jetpack-calypso/wp-jetpack-plans-spec.js

### CODE REVIEW

**Comment by alisterscott** [comment]
> Make it work with magellan code(which isn't support import statements)

@hoverduck I remember you did all the magellan set-up, is there an easy/obvious solution for this?

**Comment by hoverduck** [comment]
I toyed around with it for a bit, but couldn't find anything that worked.  It does look like recent updates to Magellan do enable es6 features (https://github.com/TestArmada/magellan/pull/192), but I know there are issues with Magellan 10.0 and the Mocha test runner, so updating may not be possible :confused:

**Comment by alisterscott** [comment]
@brbrr do you want to keep going with this, or park it for now?

**Comment by brbrr** [comment]
I think we should leave it for some better time

**Pull request closed without merging**
