### PR TITLE
Cleanup old A/B tests not running anymore

### PR DESCRIPTION
**Pull request by aidvu**

### CODE REVIEW

**Comment by alisterscott** [comment]
Thanks @aidvu - this is awesome to clean up

Comparing to master here: https://github.com/Automattic/wp-calypso/blob/master/client/lib/abtest/active-tests.js the two differences are:

`includeDotBlogSubdomainV2`
`skipDomainOrSiteStep`

Are these being removed separately?

**Comment by aidvu** [comment]
Hey @alisterscott, yep: https://github.com/Automattic/wp-calypso/pull/28393

**Comment by alisterscott** [comment]
We can ignore the Jetpack ones

**Comment by aidvu** [comment]
Jetpack failing.

**Comment by alisterscott** [comment]
@aidvu if you can rebase this it should be fine

**Comment by matthusby** [comment]
Pending the rebase this looks good to me :+1:

**Pull request merged**
