### PR TITLE
Updating test to change case of Remove text

### PR DESCRIPTION
**Pull request by bsessions85**
The remove case changed. updating test

### CODE REVIEW

**Comment by bsessions85** [comment]
Merging this to get tests passing

**Comment by alisterscott** [comment]
Was this an expected change? Could we have case insensitive match to stop this happening?

**Comment by alisterscott** [comment]
Now I think about it we probably need some form of data attribute as this will only work in English?

**Comment by bsessions85** [comment]
That is a good point.  I'll look in to it this morning and either fix or put in issue to fix later depending on how complicated it is.

**Pull request merged**
