### PR TITLE
Add new Jetpack e2e documentation

### PR DESCRIPTION
**Pull request by alisterscott**
Add some doco about configuring a new Jetpack site to run these tests against

### CODE REVIEW

**Comment by alisterscott** [comment]
@hoverduck: would you mind testing this doco to see whether you can get these tests running on a new WordPress instance? You can use the same test social media accounts if you like for ease of set up.

**Comment by hoverduck** [comment]
@alisterscott I wasn't able to get this to work.  I tried both with a local WP install on my laptop (via [this setup](https://github.com/hoverduck/falconwp)) and with a fresh Pressable site.  In both instances the connection failed, leaving me on this screen:

screen shot 2017-01-09 at 12 26 32 pm

Aside from that, I have a few suggestions for the documentation:

1. Add a step to install/activate Jetpack.  Pressable has it pre-installed, but not all hosts do.
2. If you're not using Pressable the `pressablesiteusername`/`pressablesitepassword`variable names are confusing, and should probably be renamed something generic.
3. After connecting manually (per Step Three) you're prompted to "Activate Recommended Features"...should I select that?
4. On Step Four, clarify that the Sharing page is under Settings.  First I was looking around in the Jetpack panel and couldn't find it

**Comment by alisterscott** [comment]
Thanks @hoverduck 

I'm seeing the same URL issue now. I will discuss this with the Jetpack team and work out why...

**Comment by alisterscott** [comment]
This no longer applies as Jetpack testing is done via Calypso. Closing.

**Pull request closed without merging**
