### PR TITLE
Adds a sign up for site scenario for logged in customer

### LINKED ISSUE #1557: Add a sign up test for an existing customer
This could be as simple as hitting /start signed in and make sure it loads

Or we could add a specific account for this - don't use existing account which relies on a single site in Calypso

### PR DESCRIPTION
**Pull request by alisterscott**
This extends the sign up for a free account to then add a new site to the account.

This makes sure we can sign up from a logged in state

Fixes #1557

**Testing Instructions**

Make sure "Sign up for an account only (no site) then add a site" is running and passing desktop and mobile

### CODE REVIEW

**Comment by alisterscott** [comment]
@ramonjd this _should_ catch any future sign up regressions from a logged in state

**Comment by nb** [comment]
Does this test fail if https://github.com/Automattic/wp-calypso/pull/27983 is not reverted?

**Comment by alisterscott** [comment]
> Does this test fail if Automattic/wp-calypso#27983 is not reverted?

@nb good question - I ran this against a PR I spun up with the changes that were reverted and yes it fails - see https://circleci.com/gh/Automattic/wp-e2e-tests-for-branches/13249

**Comment by nb** [comment]
Great, thanks, @alisterscott, now we’re sure the exact same bug won’t strike again :)

**Pull request merged**
