### PR TITLE
Visdiffs 2.0: Integrating visdiffs with our e2e tests

### PR DESCRIPTION
**Pull request by rachelmcr**
This PR integrates our visdiff tests with our e2e tests so we can look for visual regressions in context on WordPress.com instead of the Calypso DevDocs. The visdiffs run and take screenshots from the following tests:

- e2e tests in the `specs` directory marked with the `@visdiff` suite tag
- a new spec in the `specs-visdiff` directory (where taking a screenshot in our e2e tests would lead to unreliable results)

These visdiffs currently work on OSX Chrome, Firefox, and Safari. They currently are not working in Win IE11 or Firefox mobile; due to time constraints we are going to launch the visdiffs as-is and work to enable them in additional browsers/screensizes in the future.

**Test with Local Screenshots:**

1. Set your local config, e.g. using a config file `local-visdiff.json` with `export NODE_ENV='visdiff'`
2. Run the visdiff specs in Sauce Labs: `./run.sh -v -l [browser] -s [screensize]`
3. View the resulting screenshots in the `/wp-e2e-tests/screenshots` directory.

**Test with Applitools Screenshot Diffs:**

1. Set your local config, e.g. using a config file `local-visdiff.json` with `export NODE_ENV='visdiff'`
2. Run the visdiff specs in Sauce Labs with Applitools (requires a CircleCI token): `sh scripts/trigger-circle-ci-specific.sh Automattic/wp-e2e-tests-visdiff master $CIRCLE_TOKEN '-v -l osx-chrome -s mobile,tablet,desktop' add/integrated-visdiffs`
3. Check Slack channel for notifications from Applitools diffs or visit Applitools dashboard directly for full results.

### CODE REVIEW

**Comment by rachelmcr** [comment]
I'm working on these tests again — after a rebase they're working locally with these testing steps:

1. Set your local config, e.g. with `export NODE_ENV='personal'`
2. Set the screenshots to be taken locally with `export EYESDEBUG=1`
3. Run the visdiff test suite with `./run.sh -v`

I still need to fix the timing on a few of the screenshots to make sure the page is fully loaded before the screenshot is taken.

**Comment by bsessions85** [comment]
I've been looking through this and I don't see any issues with the code, but I am getting a test failure when I run locally. If I run on sauce it passes.

 `14:36:44       1) Can open the editor media modal
14:36:44 FAILED: Taking screenshot of: 'https://wordpress.com/post/e2evisdiffreadertesting.wordpress.com/3'
14:36:48   4 passing (45s)
14:36:48   1 failing
14:36:48   1) Calypso Visual Diff (desktop) Blog Posts: @visdiff Can open the editor media modal:
14:36:48      TimeoutError: Could not locate the newly uploaded item.
14:36:48 Wait timed out after 20559ms
14:36:48       at WebDriverError (node_modules/selenium-webdriver/lib/error.js:27:5)
14:36:48       at TimeoutError (node_modules/selenium-webdriver/lib/error.js:262:5)
14:36:48       at node_modules/selenium-webdriver/lib/promise.js:2201:17
14:36:48       at ManagedPromise.invokeCallback_ (node_modules/selenium-webdriver/lib/promise.js:1376:14)
14:36:48       at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:3084:14)
14:36:48       at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:3067:27)
14:36:48       at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2927:27)
14:36:48       at node_modules/selenium-webdriver/lib/promise.js:668:7
14:36:48       at process._tickCallback (internal/process/next_tick.js:109:7)
14:36:48   From: Task: Could not locate the newly uploaded item.
14:36:48       at scheduleWait (node_modules/selenium-webdriver/lib/promise.js:2188:20)
14:36:48       at ControlFlow.wait (node_modules/selenium-webdriver/lib/promise.js:2517:12)
14:36:48       at thenableWebDriverProxy.wait (node_modules/selenium-webdriver/lib/webdriver.js:934:29)
14:36:48       at EditorPage.selectImageByNumber (lib/pages/editor-page.js:138:17)
14:36:48       at Context.<anonymous> (specs-visdiff/wp-calypso-visdiff.js:135:20)
14:36:48       at runTest (node_modules/selenium-webdriver/testing/index.js:163:22)
14:36:48       at node_modules/selenium-webdriver/testing/index.js:184:16
14:36:48       at new ManagedPromise (node_modules/selenium-webdriver/lib/promise.js:1077:7)
14:36:48       at controlFlowExecute (node_modules/selenium-webdriver/testing/index.js:183:14)
14:36:48       at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:3084:14)
14:36:48       at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:3067:27)
14:36:48       at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2974:25)
14:36:48       at node_modules/selenium-webdriver/lib/promise.js:668:7
14:36:48   From: Task: Calypso Visual Diff (desktop) Blog Posts: @visdiff Can open the editor media modal
14:36:48       at Context.ret (node_modules/selenium-webdriver/testing/index.js:182:10)
`

**Comment by rachelmcr** [comment]
Thanks, @bsessions85! That's a weird issue — I see it now when I do a local run, too. Looks like the driver isn't properly selecting the first image in the media library. I'll see if I can find the root cause.

**Comment by rachelmcr** [comment]
Fixed the above issue. (Local test runs were happening too quickly, so we need to wait for the media modal placeholders to be replaced by actual media items before making the selection in that test. The issue didn't show up on Sauce because the test runs are _just_ enough slower.)

I've rebased and once the CI checks are passing I'll merge this.

**Pull request merged**
