### PR TITLE
[WIP] Gutenberg iFrame Tests

### PR DESCRIPTION
**Pull request by bsessions85**

### CODE REVIEW

**Comment by mmtr** [comment]
@bsessions85 @Stojdza Work is nearing completion on implementing the iframe compromise and having the e2e tests ready to flip between Gutenlypso and Gutenframe is one of our remaining blockers. Do you have any update about this?

I'm happy to help, but I'm not sure what are the remaining steps.

**Comment by Stojdza** [comment]
Hey, @mmtr Let me check the status of this one. 

Is it `add/gutenberg-iframe-tests` still active wp-calypso branch with the latest changes?

**Comment by mmtr** [comment]
> Is it `add/gutenberg-iframe-tests` still active wp-calypso branch with the latest changes?

Yep! I rebased it with master a few hours ago.

**Comment by Stojdza** [comment]
@mmtr Tests are ready. All of them are passing against wp-calypso branch `add/gutenberg-iframe-tests`

**Comment by mmtr** [comment]
@bsessions85 @Stojdza do you have any idea why the e2e tests on https://github.com/Automattic/wp-calypso/pull/30529 don't pass? That PR is for merging the Calypso branch `add/gutenberg-iframe-tests` so we're assuming they will run the e2e tests against this branch, right?

**Comment by mmtr** [comment]
I checked locally the 6 failing test and they all passed, so I'd say we can go ahead and merge this.

**Comment by Stojdza** [comment]
@mmtr I've merged latest changes from e2e master branch and run tests once again, on this PR and on wp-calypso PR, and both run passed. 

Feel free to merge this PR together with https://github.com/Automattic/wp-calypso/pull/30529

**Comment by rodrigoi** [comment]
🚀 🌕

**Pull request merged**
